# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        script:
        # install chromium and dependencies
        - apt-get update && apt-get install -yq libgconf-2-4
        - >
          apt-get update && apt-get install -y wget --no-install-recommends && \
             wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -  && \
             sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
             apt-get update && \
             apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont --no-install-recommends
             # Dont worry about cleaning up files left after installation.
          - npm install
          - npm run HxUi-UnitTests
          - npm run HxUi-Build
  pull-requests:
    '**': #this runs as default for any branch not elsewhere defined
      - step:
         script:
         # install chromium and dependencies
         - apt-get update && apt-get install -yq libgconf-2-4
         - >
           apt-get update && apt-get install -y wget --no-install-recommends && \
              wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -  && \
              sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
              apt-get update && \
              apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont --no-install-recommends
              # Dont worry about cleaning up files left after installation.
           - npm install
           - npm run HxUi-UnitTests
           - npm run HxUi-Build
